/*
###############################################################
#  Generated by:      Cadence Innovus 17.16-s058_1
#  OS:                Linux x86_64(Host ID kl3313-05.ece.gatech.edu)
#  Generated on:      Mon May 17 11:25:12 2021
#  Design:            spi_module
#  Command:           saveDesign -rc -verilog -def ./data/dbs/postroute/spi_module -nocompress
###############################################################
*/
module spi_module (
	config_delay_matrix_element0, 
	config_delay_matrix_element1, 
	config_delay_matrix_element2, 
	config_delay_matrix_element3, 
	config_obj_id_element0, 
	config_obj_id_element1, 
	config_obj_id_element2, 
	config_obj_id_element3, 
	CLK, 
	reset, 
	delay_matrix_element, 
	obj_id_element, 
	load);
   input [13:0] config_delay_matrix_element0;
   input [13:0] config_delay_matrix_element1;
   input [13:0] config_delay_matrix_element2;
   input [13:0] config_delay_matrix_element3;
   input [1:0] config_obj_id_element0;
   input [1:0] config_obj_id_element1;
   input [1:0] config_obj_id_element2;
   input [1:0] config_obj_id_element3;
   input CLK;
   input reset;
   output [13:0] delay_matrix_element;
   output [1:0] obj_id_element;
   input load;

   // Internal wires
   wire N23;
   wire N24;
   wire N25;
   wire N26;
   wire N27;
   wire N28;
   wire N29;
   wire N30;
   wire N31;
   wire N32;
   wire N33;
   wire N34;
   wire N35;
   wire N36;
   wire N37;
   wire N38;
   wire N39;
   wire N40;
   wire n38;
   wire n120;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n131;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n136;
   wire n137;
   wire n138;
   wire n139;
   wire n140;
   wire n141;
   wire n142;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n151;
   wire n152;
   wire n153;
   wire n154;
   wire n155;
   wire n156;
   wire n172;
   wire [1:0] cnt;
   wire [7:0] din_obj_reg;
   wire [55:0] din_reg;

   LHCNDQD1BWP30P140LVT din_obj_reg_reg_3__1_ (.CDN(n38),
	.D(config_obj_id_element3[1]),
	.E(load),
	.Q(din_obj_reg[7]));
   LHCNDQD1BWP30P140LVT din_obj_reg_reg_3__0_ (.CDN(n38),
	.D(config_obj_id_element3[0]),
	.E(load),
	.Q(din_obj_reg[6]));
   LHCNDQD1BWP30P140LVT din_obj_reg_reg_2__1_ (.CDN(n38),
	.D(config_obj_id_element2[1]),
	.E(load),
	.Q(din_obj_reg[5]));
   LHCNDQD1BWP30P140LVT din_obj_reg_reg_2__0_ (.CDN(n38),
	.D(config_obj_id_element2[0]),
	.E(load),
	.Q(din_obj_reg[4]));
   LHCNDQD1BWP30P140LVT din_obj_reg_reg_1__1_ (.CDN(n38),
	.D(config_obj_id_element1[1]),
	.E(load),
	.Q(din_obj_reg[3]));
   LHCNDQD1BWP30P140LVT din_obj_reg_reg_1__0_ (.CDN(n38),
	.D(config_obj_id_element1[0]),
	.E(load),
	.Q(din_obj_reg[2]));
   LHCNDQD1BWP30P140LVT din_obj_reg_reg_0__1_ (.CDN(n38),
	.D(config_obj_id_element0[1]),
	.E(load),
	.Q(din_obj_reg[1]));
   LHCNDQD1BWP30P140LVT din_obj_reg_reg_0__0_ (.CDN(n38),
	.D(config_obj_id_element0[0]),
	.E(load),
	.Q(din_obj_reg[0]));
   LHCNDQD1BWP30P140LVT din_reg_reg_3__13_ (.CDN(n38),
	.D(config_delay_matrix_element3[13]),
	.E(load),
	.Q(din_reg[55]));
   LHCNDQD1BWP30P140LVT din_reg_reg_3__12_ (.CDN(n38),
	.D(config_delay_matrix_element3[12]),
	.E(load),
	.Q(din_reg[54]));
   LHCNDQD1BWP30P140LVT din_reg_reg_3__11_ (.CDN(n38),
	.D(config_delay_matrix_element3[11]),
	.E(load),
	.Q(din_reg[53]));
   LHCNDQD1BWP30P140LVT din_reg_reg_3__10_ (.CDN(n38),
	.D(config_delay_matrix_element3[10]),
	.E(load),
	.Q(din_reg[52]));
   LHCNDQD1BWP30P140LVT din_reg_reg_3__9_ (.CDN(n38),
	.D(config_delay_matrix_element3[9]),
	.E(load),
	.Q(din_reg[51]));
   LHCNDQD1BWP30P140LVT din_reg_reg_3__8_ (.CDN(n38),
	.D(config_delay_matrix_element3[8]),
	.E(load),
	.Q(din_reg[50]));
   LHCNDQD1BWP30P140LVT din_reg_reg_3__7_ (.CDN(n38),
	.D(config_delay_matrix_element3[7]),
	.E(load),
	.Q(din_reg[49]));
   LHCNDQD1BWP30P140LVT din_reg_reg_3__6_ (.CDN(n38),
	.D(config_delay_matrix_element3[6]),
	.E(load),
	.Q(din_reg[48]));
   LHCNDQD1BWP30P140LVT din_reg_reg_3__5_ (.CDN(n38),
	.D(config_delay_matrix_element3[5]),
	.E(load),
	.Q(din_reg[47]));
   LHCNDQD1BWP30P140LVT din_reg_reg_3__4_ (.CDN(n38),
	.D(config_delay_matrix_element3[4]),
	.E(load),
	.Q(din_reg[46]));
   LHCNDQD1BWP30P140LVT din_reg_reg_3__3_ (.CDN(n38),
	.D(config_delay_matrix_element3[3]),
	.E(load),
	.Q(din_reg[45]));
   LHCNDQD1BWP30P140LVT din_reg_reg_3__2_ (.CDN(n38),
	.D(config_delay_matrix_element3[2]),
	.E(load),
	.Q(din_reg[44]));
   LHCNDQD1BWP30P140LVT din_reg_reg_3__1_ (.CDN(n38),
	.D(config_delay_matrix_element3[1]),
	.E(load),
	.Q(din_reg[43]));
   LHCNDQD1BWP30P140LVT din_reg_reg_3__0_ (.CDN(n38),
	.D(config_delay_matrix_element3[0]),
	.E(load),
	.Q(din_reg[42]));
   LHCNDQD1BWP30P140LVT din_reg_reg_2__13_ (.CDN(n38),
	.D(config_delay_matrix_element2[13]),
	.E(load),
	.Q(din_reg[41]));
   LHCNDQD1BWP30P140LVT din_reg_reg_2__12_ (.CDN(n38),
	.D(config_delay_matrix_element2[12]),
	.E(load),
	.Q(din_reg[40]));
   LHCNDQD1BWP30P140LVT din_reg_reg_2__11_ (.CDN(n38),
	.D(config_delay_matrix_element2[11]),
	.E(load),
	.Q(din_reg[39]));
   LHCNDQD1BWP30P140LVT din_reg_reg_2__10_ (.CDN(n38),
	.D(config_delay_matrix_element2[10]),
	.E(load),
	.Q(din_reg[38]));
   LHCNDQD1BWP30P140LVT din_reg_reg_2__9_ (.CDN(n38),
	.D(config_delay_matrix_element2[9]),
	.E(load),
	.Q(din_reg[37]));
   LHCNDQD1BWP30P140LVT din_reg_reg_2__8_ (.CDN(n38),
	.D(config_delay_matrix_element2[8]),
	.E(load),
	.Q(din_reg[36]));
   LHCNDQD1BWP30P140LVT din_reg_reg_2__7_ (.CDN(n38),
	.D(config_delay_matrix_element2[7]),
	.E(load),
	.Q(din_reg[35]));
   LHCNDQD1BWP30P140LVT din_reg_reg_2__6_ (.CDN(n38),
	.D(config_delay_matrix_element2[6]),
	.E(load),
	.Q(din_reg[34]));
   LHCNDQD1BWP30P140LVT din_reg_reg_2__5_ (.CDN(n38),
	.D(config_delay_matrix_element2[5]),
	.E(load),
	.Q(din_reg[33]));
   LHCNDQD1BWP30P140LVT din_reg_reg_2__4_ (.CDN(n38),
	.D(config_delay_matrix_element2[4]),
	.E(load),
	.Q(din_reg[32]));
   LHCNDQD1BWP30P140LVT din_reg_reg_2__3_ (.CDN(n38),
	.D(config_delay_matrix_element2[3]),
	.E(load),
	.Q(din_reg[31]));
   LHCNDQD1BWP30P140LVT din_reg_reg_2__2_ (.CDN(n38),
	.D(config_delay_matrix_element2[2]),
	.E(load),
	.Q(din_reg[30]));
   LHCNDQD1BWP30P140LVT din_reg_reg_2__1_ (.CDN(n38),
	.D(config_delay_matrix_element2[1]),
	.E(load),
	.Q(din_reg[29]));
   LHCNDQD1BWP30P140LVT din_reg_reg_2__0_ (.CDN(n38),
	.D(config_delay_matrix_element2[0]),
	.E(load),
	.Q(din_reg[28]));
   LHCNDQD1BWP30P140LVT din_reg_reg_1__13_ (.CDN(n38),
	.D(config_delay_matrix_element1[13]),
	.E(load),
	.Q(din_reg[27]));
   LHCNDQD1BWP30P140LVT din_reg_reg_1__12_ (.CDN(n38),
	.D(config_delay_matrix_element1[12]),
	.E(load),
	.Q(din_reg[26]));
   LHCNDQD1BWP30P140LVT din_reg_reg_1__11_ (.CDN(n38),
	.D(config_delay_matrix_element1[11]),
	.E(load),
	.Q(din_reg[25]));
   LHCNDQD1BWP30P140LVT din_reg_reg_1__10_ (.CDN(n38),
	.D(config_delay_matrix_element1[10]),
	.E(load),
	.Q(din_reg[24]));
   LHCNDQD1BWP30P140LVT din_reg_reg_1__9_ (.CDN(n38),
	.D(config_delay_matrix_element1[9]),
	.E(load),
	.Q(din_reg[23]));
   LHCNDQD1BWP30P140LVT din_reg_reg_1__8_ (.CDN(n38),
	.D(config_delay_matrix_element1[8]),
	.E(load),
	.Q(din_reg[22]));
   LHCNDQD1BWP30P140LVT din_reg_reg_1__7_ (.CDN(n38),
	.D(config_delay_matrix_element1[7]),
	.E(load),
	.Q(din_reg[21]));
   LHCNDQD1BWP30P140LVT din_reg_reg_1__6_ (.CDN(n38),
	.D(config_delay_matrix_element1[6]),
	.E(load),
	.Q(din_reg[20]));
   LHCNDQD1BWP30P140LVT din_reg_reg_1__5_ (.CDN(n38),
	.D(config_delay_matrix_element1[5]),
	.E(load),
	.Q(din_reg[19]));
   LHCNDQD1BWP30P140LVT din_reg_reg_1__4_ (.CDN(n38),
	.D(config_delay_matrix_element1[4]),
	.E(load),
	.Q(din_reg[18]));
   LHCNDQD1BWP30P140LVT din_reg_reg_1__3_ (.CDN(n38),
	.D(config_delay_matrix_element1[3]),
	.E(load),
	.Q(din_reg[17]));
   LHCNDQD1BWP30P140LVT din_reg_reg_1__2_ (.CDN(n38),
	.D(config_delay_matrix_element1[2]),
	.E(load),
	.Q(din_reg[16]));
   LHCNDQD1BWP30P140LVT din_reg_reg_1__1_ (.CDN(n38),
	.D(config_delay_matrix_element1[1]),
	.E(load),
	.Q(din_reg[15]));
   LHCNDQD1BWP30P140LVT din_reg_reg_1__0_ (.CDN(n38),
	.D(config_delay_matrix_element1[0]),
	.E(load),
	.Q(din_reg[14]));
   LHCNDQD1BWP30P140LVT din_reg_reg_0__13_ (.CDN(n38),
	.D(config_delay_matrix_element0[13]),
	.E(load),
	.Q(din_reg[13]));
   LHCNDQD1BWP30P140LVT din_reg_reg_0__12_ (.CDN(n38),
	.D(config_delay_matrix_element0[12]),
	.E(load),
	.Q(din_reg[12]));
   LHCNDQD1BWP30P140LVT din_reg_reg_0__11_ (.CDN(n38),
	.D(config_delay_matrix_element0[11]),
	.E(load),
	.Q(din_reg[11]));
   LHCNDQD1BWP30P140LVT din_reg_reg_0__10_ (.CDN(n38),
	.D(config_delay_matrix_element0[10]),
	.E(load),
	.Q(din_reg[10]));
   LHCNDQD1BWP30P140LVT din_reg_reg_0__9_ (.CDN(n38),
	.D(config_delay_matrix_element0[9]),
	.E(load),
	.Q(din_reg[9]));
   LHCNDQD1BWP30P140LVT din_reg_reg_0__8_ (.CDN(n38),
	.D(config_delay_matrix_element0[8]),
	.E(load),
	.Q(din_reg[8]));
   LHCNDQD1BWP30P140LVT din_reg_reg_0__7_ (.CDN(n38),
	.D(config_delay_matrix_element0[7]),
	.E(load),
	.Q(din_reg[7]));
   LHCNDQD1BWP30P140LVT din_reg_reg_0__6_ (.CDN(n38),
	.D(config_delay_matrix_element0[6]),
	.E(load),
	.Q(din_reg[6]));
   LHCNDQD1BWP30P140LVT din_reg_reg_0__5_ (.CDN(n38),
	.D(config_delay_matrix_element0[5]),
	.E(load),
	.Q(din_reg[5]));
   LHCNDQD1BWP30P140LVT din_reg_reg_0__4_ (.CDN(n38),
	.D(config_delay_matrix_element0[4]),
	.E(load),
	.Q(din_reg[4]));
   LHCNDQD1BWP30P140LVT din_reg_reg_0__3_ (.CDN(n38),
	.D(config_delay_matrix_element0[3]),
	.E(load),
	.Q(din_reg[3]));
   LHCNDQD1BWP30P140LVT din_reg_reg_0__2_ (.CDN(n38),
	.D(config_delay_matrix_element0[2]),
	.E(load),
	.Q(din_reg[2]));
   LHCNDQD1BWP30P140LVT din_reg_reg_0__1_ (.CDN(n38),
	.D(config_delay_matrix_element0[1]),
	.E(load),
	.Q(din_reg[1]));
   LHCNDQD1BWP30P140LVT din_reg_reg_0__0_ (.CDN(n38),
	.D(config_delay_matrix_element0[0]),
	.E(load),
	.Q(din_reg[0]));
   EDFCNQD1BWP30P140LVT cnt_reg_0_ (.CDN(n38),
	.CP(CLK),
	.D(N39),
	.E(n120),
	.Q(cnt[0]));
   EDFCNQD2BWP30P140LVT delay_matrix_element_reg_13_ (.CDN(n38),
	.CP(CLK),
	.D(N36),
	.E(n120),
	.Q(delay_matrix_element[13]));
   EDFCND1BWP30P140LVT cnt_reg_1_ (.CDN(n38),
	.CP(CLK),
	.D(N40),
	.E(n120),
	.Q(cnt[1]),
	.QN(n172));
   EDFCNQD2BWP30P140LVT delay_matrix_element_reg_12_ (.CDN(n38),
	.CP(CLK),
	.D(N35),
	.E(n120),
	.Q(delay_matrix_element[12]));
   EDFCNQD2BWP30P140LVT delay_matrix_element_reg_11_ (.CDN(n38),
	.CP(CLK),
	.D(N34),
	.E(n120),
	.Q(delay_matrix_element[11]));
   EDFCNQD2BWP30P140LVT delay_matrix_element_reg_10_ (.CDN(n38),
	.CP(CLK),
	.D(N33),
	.E(n120),
	.Q(delay_matrix_element[10]));
   EDFCNQD2BWP30P140LVT delay_matrix_element_reg_9_ (.CDN(n38),
	.CP(CLK),
	.D(N32),
	.E(n120),
	.Q(delay_matrix_element[9]));
   EDFCNQD2BWP30P140LVT delay_matrix_element_reg_8_ (.CDN(n38),
	.CP(CLK),
	.D(N31),
	.E(n120),
	.Q(delay_matrix_element[8]));
   EDFCNQD2BWP30P140LVT delay_matrix_element_reg_7_ (.CDN(n38),
	.CP(CLK),
	.D(N30),
	.E(n120),
	.Q(delay_matrix_element[7]));
   EDFCNQD2BWP30P140LVT delay_matrix_element_reg_6_ (.CDN(n38),
	.CP(CLK),
	.D(N29),
	.E(n120),
	.Q(delay_matrix_element[6]));
   EDFCNQD2BWP30P140LVT delay_matrix_element_reg_5_ (.CDN(n38),
	.CP(CLK),
	.D(N28),
	.E(n120),
	.Q(delay_matrix_element[5]));
   EDFCNQD2BWP30P140LVT delay_matrix_element_reg_4_ (.CDN(n38),
	.CP(CLK),
	.D(N27),
	.E(n120),
	.Q(delay_matrix_element[4]));
   EDFCNQD2BWP30P140LVT delay_matrix_element_reg_3_ (.CDN(n38),
	.CP(CLK),
	.D(N26),
	.E(n120),
	.Q(delay_matrix_element[3]));
   EDFCNQD2BWP30P140LVT delay_matrix_element_reg_2_ (.CDN(n38),
	.CP(CLK),
	.D(N25),
	.E(n120),
	.Q(delay_matrix_element[2]));
   EDFCNQD2BWP30P140LVT delay_matrix_element_reg_1_ (.CDN(n38),
	.CP(CLK),
	.D(N24),
	.E(n120),
	.Q(delay_matrix_element[1]));
   EDFCNQD2BWP30P140LVT delay_matrix_element_reg_0_ (.CDN(n38),
	.CP(CLK),
	.D(N23),
	.E(n120),
	.Q(delay_matrix_element[0]));
   EDFCNQD2BWP30P140LVT obj_id_element_reg_1_ (.CDN(n38),
	.CP(CLK),
	.D(N38),
	.E(n120),
	.Q(obj_id_element[1]));
   EDFCNQD2BWP30P140LVT obj_id_element_reg_0_ (.CDN(n38),
	.CP(CLK),
	.D(N37),
	.E(n120),
	.Q(obj_id_element[0]));
   NR2D1P5BWP30P140LVT U60 (.A1(N39),
	.A2(n172),
	.ZN(n152));
   NR2OPTPAD1BWP30P140LVT U61 (.A1(cnt[0]),
	.A2(cnt[1]),
	.ZN(n151));
   NR2OPTIBD2BWP30P140LVT U62 (.A1(cnt[0]),
	.A2(n172),
	.ZN(n155));
   NR2D1BWP30P140LVT U63 (.A1(cnt[1]),
	.A2(N39),
	.ZN(n156));
   ND2D0BWP30P140LVT U64 (.A1(n122),
	.A2(n121),
	.ZN(N36));
   ND2D0BWP30P140LVT U65 (.A1(n136),
	.A2(n135),
	.ZN(N37));
   ND2D0BWP30P140LVT U66 (.A1(n140),
	.A2(n139),
	.ZN(N38));
   ND2D0BWP30P140LVT U67 (.A1(n134),
	.A2(n133),
	.ZN(N23));
   ND2D0BWP30P140LVT U68 (.A1(n132),
	.A2(n131),
	.ZN(N24));
   ND2D0BWP30P140LVT U69 (.A1(n150),
	.A2(n149),
	.ZN(N25));
   ND2D0BWP30P140LVT U70 (.A1(n148),
	.A2(n147),
	.ZN(N26));
   ND2D0BWP30P140LVT U71 (.A1(n146),
	.A2(n145),
	.ZN(N27));
   ND2D0BWP30P140LVT U72 (.A1(n144),
	.A2(n143),
	.ZN(N28));
   ND2D1BWP30P140LVT U73 (.A1(n142),
	.A2(n141),
	.ZN(N29));
   ND2D0BWP30P140LVT U74 (.A1(n154),
	.A2(n153),
	.ZN(N30));
   ND2D0BWP30P140LVT U75 (.A1(n138),
	.A2(n137),
	.ZN(N31));
   ND2D0BWP30P140LVT U76 (.A1(n130),
	.A2(n129),
	.ZN(N32));
   ND2D0BWP30P140LVT U77 (.A1(n128),
	.A2(n127),
	.ZN(N33));
   ND2D0BWP30P140LVT U78 (.A1(n126),
	.A2(n125),
	.ZN(N34));
   ND2D0BWP30P140LVT U79 (.A1(n124),
	.A2(n123),
	.ZN(N35));
   ND2OPTIBD2BWP30P140LVT U80 (.A1(load),
	.A2(n38),
	.ZN(n120));
   INVD0P7BWP30P140LVT U81 (.I(cnt[0]),
	.ZN(N39));
   CKND6BWP30P140LVT U82 (.I(reset),
	.ZN(n38));
   AOI22D0BWP30P140LVT U83 (.A1(n156),
	.A2(din_reg[27]),
	.B1(n155),
	.B2(din_reg[41]),
	.ZN(n122));
   AOI22D0BWP30P140LVT U84 (.A1(n152),
	.A2(din_reg[55]),
	.B1(n151),
	.B2(din_reg[13]),
	.ZN(n121));
   AOI22D0BWP30P140LVT U85 (.A1(n156),
	.A2(din_reg[26]),
	.B1(n155),
	.B2(din_reg[40]),
	.ZN(n124));
   AOI22D0BWP30P140LVT U86 (.A1(n152),
	.A2(din_reg[54]),
	.B1(n151),
	.B2(din_reg[12]),
	.ZN(n123));
   AOI22D0BWP30P140LVT U87 (.A1(n156),
	.A2(din_reg[25]),
	.B1(n155),
	.B2(din_reg[39]),
	.ZN(n126));
   AOI22D0BWP30P140LVT U88 (.A1(n152),
	.A2(din_reg[53]),
	.B1(n151),
	.B2(din_reg[11]),
	.ZN(n125));
   AOI22D0BWP30P140LVT U89 (.A1(n156),
	.A2(din_reg[24]),
	.B1(n155),
	.B2(din_reg[38]),
	.ZN(n128));
   AOI22D0BWP30P140LVT U90 (.A1(n152),
	.A2(din_reg[52]),
	.B1(n151),
	.B2(din_reg[10]),
	.ZN(n127));
   AOI22D0BWP30P140LVT U91 (.A1(n156),
	.A2(din_reg[23]),
	.B1(n155),
	.B2(din_reg[37]),
	.ZN(n130));
   AOI22D0BWP30P140LVT U92 (.A1(n152),
	.A2(din_reg[51]),
	.B1(n151),
	.B2(din_reg[9]),
	.ZN(n129));
   AOI22D0BWP30P140LVT U93 (.A1(n156),
	.A2(din_reg[15]),
	.B1(n155),
	.B2(din_reg[29]),
	.ZN(n132));
   AOI22D0BWP30P140LVT U94 (.A1(n152),
	.A2(din_reg[43]),
	.B1(n151),
	.B2(din_reg[1]),
	.ZN(n131));
   AOI22D0BWP30P140LVT U95 (.A1(n156),
	.A2(din_reg[14]),
	.B1(n155),
	.B2(din_reg[28]),
	.ZN(n134));
   AOI22D0BWP30P140LVT U96 (.A1(n152),
	.A2(din_reg[42]),
	.B1(n151),
	.B2(din_reg[0]),
	.ZN(n133));
   AOI22D0BWP30P140LVT U97 (.A1(n156),
	.A2(din_obj_reg[2]),
	.B1(n155),
	.B2(din_obj_reg[4]),
	.ZN(n136));
   AOI22D0BWP30P140LVT U98 (.A1(n152),
	.A2(din_obj_reg[6]),
	.B1(n151),
	.B2(din_obj_reg[0]),
	.ZN(n135));
   AOI22D0BWP30P140LVT U99 (.A1(n156),
	.A2(din_reg[22]),
	.B1(n155),
	.B2(din_reg[36]),
	.ZN(n138));
   AOI22D0BWP30P140LVT U100 (.A1(n152),
	.A2(din_reg[50]),
	.B1(n151),
	.B2(din_reg[8]),
	.ZN(n137));
   AOI22D0BWP30P140LVT U101 (.A1(n156),
	.A2(din_obj_reg[3]),
	.B1(n155),
	.B2(din_obj_reg[5]),
	.ZN(n140));
   AOI22D0BWP30P140LVT U102 (.A1(n152),
	.A2(din_obj_reg[7]),
	.B1(n151),
	.B2(din_obj_reg[1]),
	.ZN(n139));
   AOI22D0BWP30P140LVT U103 (.A1(n156),
	.A2(din_reg[20]),
	.B1(n155),
	.B2(din_reg[34]),
	.ZN(n142));
   AOI22D0BWP30P140LVT U104 (.A1(n152),
	.A2(din_reg[48]),
	.B1(n151),
	.B2(din_reg[6]),
	.ZN(n141));
   AOI22D0BWP30P140LVT U105 (.A1(n156),
	.A2(din_reg[19]),
	.B1(n155),
	.B2(din_reg[33]),
	.ZN(n144));
   AOI22D0BWP30P140LVT U106 (.A1(n152),
	.A2(din_reg[47]),
	.B1(n151),
	.B2(din_reg[5]),
	.ZN(n143));
   AOI22D0BWP30P140LVT U107 (.A1(n156),
	.A2(din_reg[18]),
	.B1(n155),
	.B2(din_reg[32]),
	.ZN(n146));
   AOI22D0BWP30P140LVT U108 (.A1(n152),
	.A2(din_reg[46]),
	.B1(n151),
	.B2(din_reg[4]),
	.ZN(n145));
   AOI22D0BWP30P140LVT U109 (.A1(n156),
	.A2(din_reg[17]),
	.B1(n155),
	.B2(din_reg[31]),
	.ZN(n148));
   AOI22D0BWP30P140LVT U110 (.A1(n152),
	.A2(din_reg[45]),
	.B1(n151),
	.B2(din_reg[3]),
	.ZN(n147));
   AOI22D0BWP30P140LVT U111 (.A1(n156),
	.A2(din_reg[16]),
	.B1(n155),
	.B2(din_reg[30]),
	.ZN(n150));
   AOI22D0BWP30P140LVT U112 (.A1(n152),
	.A2(din_reg[44]),
	.B1(n151),
	.B2(din_reg[2]),
	.ZN(n149));
   AOI22D0BWP30P140LVT U113 (.A1(n156),
	.A2(din_reg[21]),
	.B1(n155),
	.B2(din_reg[35]),
	.ZN(n154));
   AOI22D0BWP30P140LVT U114 (.A1(n152),
	.A2(din_reg[49]),
	.B1(n151),
	.B2(din_reg[7]),
	.ZN(n153));
   OR2D0BWP30P140LVT U115 (.A1(n156),
	.A2(n155),
	.Z(N40));
endmodule

