###################################################################

# Created by write_sdc on Sat Jun 19 03:59:10 2021

###################################################################
set sdc_version 2.0

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_driving_cell -min -lib_cell BUFFD2BWP30P140 [get_ports clk]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports rst]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_valid[7]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_valid[6]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_valid[5]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_valid[4]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_valid[3]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_valid[2]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_valid[1]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_valid[0]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[255]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[254]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[253]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[252]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[251]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[250]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[249]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[248]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[247]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[246]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[245]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[244]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[243]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[242]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[241]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[240]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[239]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[238]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[237]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[236]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[235]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[234]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[233]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[232]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[231]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[230]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[229]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[228]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[227]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[226]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[225]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[224]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[223]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[222]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[221]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[220]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[219]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[218]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[217]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[216]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[215]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[214]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[213]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[212]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[211]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[210]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[209]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[208]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[207]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[206]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[205]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[204]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[203]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[202]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[201]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[200]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[199]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[198]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[197]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[196]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[195]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[194]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[193]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[192]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[191]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[190]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[189]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[188]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[187]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[186]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[185]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[184]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[183]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[182]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[181]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[180]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[179]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[178]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[177]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[176]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[175]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[174]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[173]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[172]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[171]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[170]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[169]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[168]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[167]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[166]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[165]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[164]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[163]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[162]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[161]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[160]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[159]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[158]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[157]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[156]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[155]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[154]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[153]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[152]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[151]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[150]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[149]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[148]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[147]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[146]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[145]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[144]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[143]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[142]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[141]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[140]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[139]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[138]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[137]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[136]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[135]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[134]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[133]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[132]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[131]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[130]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[129]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[128]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[127]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[126]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[125]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[124]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[123]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[122]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[121]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[120]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[119]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[118]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[117]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[116]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[115]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[114]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[113]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[112]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[111]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[110]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[109]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[108]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[107]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[106]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[105]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[104]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[103]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[102]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[101]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[100]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[99]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[98]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[97]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[96]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[95]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[94]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[93]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[92]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[91]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[90]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[89]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[88]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[87]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[86]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[85]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[84]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[83]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[82]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[81]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[80]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[79]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[78]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[77]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[76]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[75]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[74]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[73]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[72]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[71]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[70]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[69]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[68]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[67]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[66]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[65]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[64]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[63]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[62]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[61]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[60]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[59]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[58]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[57]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[56]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[55]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[54]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[53]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[52]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[51]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[50]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[49]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[48]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[47]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[46]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[45]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[44]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[43]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[42]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[41]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[40]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[39]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[38]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[37]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[36]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[35]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[34]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[33]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[32]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[31]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[30]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[29]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[28]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[27]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[26]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[25]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[24]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[23]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[22]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[21]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[20]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[19]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[18]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[17]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[16]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[15]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[14]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[13]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[12]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[11]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[10]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[9]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[8]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[7]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[6]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[5]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[4]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[3]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[2]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[1]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_data_bus[0]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports i_en]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[39]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[38]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[37]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[36]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[35]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[34]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[33]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[32]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[31]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[30]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[29]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[28]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[27]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[26]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[25]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[24]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[23]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[22]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[21]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[20]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[19]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[18]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[17]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[16]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[15]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[14]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[13]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[12]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[11]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[10]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[9]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[8]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[7]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[6]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[5]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[4]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[3]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[2]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[1]}]
set_driving_cell -lib_cell BUFFD2BWP30P140 [get_ports {i_cmd[0]}]
set_load -pin_load 0.1 [get_ports {o_valid[7]}]
set_load -pin_load 0.1 [get_ports {o_valid[6]}]
set_load -pin_load 0.1 [get_ports {o_valid[5]}]
set_load -pin_load 0.1 [get_ports {o_valid[4]}]
set_load -pin_load 0.1 [get_ports {o_valid[3]}]
set_load -pin_load 0.1 [get_ports {o_valid[2]}]
set_load -pin_load 0.1 [get_ports {o_valid[1]}]
set_load -pin_load 0.1 [get_ports {o_valid[0]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[255]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[254]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[253]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[252]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[251]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[250]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[249]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[248]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[247]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[246]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[245]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[244]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[243]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[242]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[241]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[240]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[239]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[238]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[237]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[236]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[235]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[234]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[233]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[232]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[231]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[230]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[229]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[228]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[227]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[226]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[225]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[224]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[223]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[222]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[221]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[220]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[219]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[218]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[217]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[216]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[215]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[214]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[213]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[212]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[211]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[210]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[209]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[208]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[207]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[206]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[205]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[204]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[203]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[202]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[201]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[200]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[199]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[198]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[197]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[196]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[195]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[194]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[193]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[192]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[191]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[190]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[189]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[188]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[187]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[186]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[185]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[184]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[183]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[182]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[181]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[180]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[179]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[178]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[177]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[176]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[175]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[174]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[173]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[172]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[171]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[170]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[169]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[168]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[167]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[166]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[165]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[164]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[163]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[162]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[161]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[160]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[159]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[158]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[157]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[156]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[155]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[154]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[153]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[152]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[151]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[150]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[149]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[148]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[147]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[146]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[145]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[144]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[143]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[142]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[141]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[140]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[139]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[138]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[137]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[136]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[135]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[134]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[133]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[132]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[131]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[130]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[129]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[128]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[127]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[126]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[125]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[124]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[123]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[122]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[121]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[120]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[119]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[118]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[117]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[116]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[115]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[114]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[113]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[112]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[111]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[110]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[109]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[108]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[107]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[106]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[105]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[104]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[103]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[102]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[101]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[100]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[99]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[98]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[97]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[96]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[95]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[94]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[93]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[92]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[91]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[90]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[89]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[88]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[87]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[86]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[85]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[84]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[83]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[82]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[81]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[80]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[79]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[78]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[77]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[76]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[75]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[74]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[73]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[72]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[71]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[70]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[69]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[68]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[67]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[66]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[65]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[64]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[63]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[62]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[61]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[60]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[59]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[58]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[57]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[56]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[55]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[54]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[53]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[52]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[51]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[50]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[49]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[48]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[47]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[46]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[45]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[44]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[43]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[42]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[41]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[40]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[39]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[38]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[37]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[36]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[35]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[34]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[33]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[32]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[31]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[30]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[29]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[28]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[27]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[26]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[25]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[24]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[23]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[22]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[21]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[20]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[19]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[18]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[17]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[16]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[15]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[14]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[13]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[12]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[11]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[10]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[9]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[8]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[7]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[6]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[5]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[4]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[3]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[2]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[1]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[0]}]
create_clock [get_ports clk]  -name clk  -period 0.3  -waveform {0 0.15}  -add
set_clock_uncertainty -setup 0.15  [get_clocks clk]
set_false_path   -from [list [get_ports rst] [get_ports i_en]]
set_input_delay -clock clk  0.06  [get_ports rst]
set_input_delay -clock clk  0.06  [get_ports i_en]
set_input_delay -clock clk  0.06  [get_ports {i_valid[7]}]
set_input_delay -clock clk  0.06  [get_ports {i_valid[6]}]
set_input_delay -clock clk  0.06  [get_ports {i_valid[5]}]
set_input_delay -clock clk  0.06  [get_ports {i_valid[4]}]
set_input_delay -clock clk  0.06  [get_ports {i_valid[3]}]
set_input_delay -clock clk  0.06  [get_ports {i_valid[2]}]
set_input_delay -clock clk  0.06  [get_ports {i_valid[1]}]
set_input_delay -clock clk  0.06  [get_ports {i_valid[0]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[255]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[254]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[253]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[252]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[251]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[250]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[249]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[248]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[247]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[246]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[245]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[244]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[243]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[242]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[241]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[240]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[239]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[238]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[237]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[236]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[235]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[234]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[233]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[232]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[231]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[230]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[229]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[228]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[227]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[226]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[225]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[224]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[223]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[222]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[221]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[220]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[219]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[218]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[217]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[216]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[215]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[214]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[213]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[212]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[211]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[210]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[209]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[208]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[207]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[206]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[205]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[204]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[203]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[202]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[201]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[200]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[199]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[198]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[197]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[196]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[195]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[194]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[193]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[192]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[191]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[190]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[189]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[188]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[187]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[186]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[185]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[184]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[183]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[182]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[181]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[180]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[179]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[178]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[177]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[176]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[175]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[174]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[173]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[172]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[171]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[170]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[169]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[168]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[167]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[166]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[165]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[164]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[163]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[162]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[161]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[160]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[159]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[158]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[157]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[156]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[155]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[154]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[153]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[152]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[151]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[150]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[149]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[148]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[147]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[146]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[145]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[144]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[143]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[142]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[141]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[140]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[139]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[138]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[137]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[136]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[135]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[134]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[133]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[132]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[131]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[130]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[129]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[128]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[127]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[126]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[125]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[124]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[123]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[122]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[121]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[120]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[119]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[118]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[117]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[116]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[115]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[114]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[113]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[112]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[111]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[110]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[109]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[108]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[107]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[106]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[105]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[104]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[103]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[102]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[101]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[100]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[99]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[98]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[97]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[96]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[95]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[94]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[93]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[92]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[91]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[90]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[89]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[88]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[87]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[86]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[85]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[84]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[83]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[82]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[81]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[80]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[79]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[78]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[77]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[76]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[75]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[74]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[73]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[72]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[71]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[70]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[69]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[68]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[67]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[66]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[65]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[64]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[63]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[62]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[61]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[60]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[59]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[58]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[57]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[56]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[55]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[54]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[53]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[52]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[51]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[50]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[49]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[48]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[47]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[46]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[45]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[44]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[43]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[42]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[41]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[40]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[39]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[38]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[37]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[36]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[35]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[34]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[33]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[32]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[31]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[30]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[29]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[28]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[27]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[26]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[25]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[24]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[23]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[22]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[21]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[20]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[19]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[18]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[17]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[16]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[15]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[14]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[13]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[12]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[11]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[10]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[9]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[8]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[7]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[6]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[5]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[4]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[3]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[2]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[1]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[0]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[39]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[38]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[37]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[36]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[35]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[34]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[33]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[32]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[31]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[30]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[29]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[28]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[27]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[26]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[25]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[24]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[23]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[22]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[21]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[20]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[19]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[18]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[17]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[16]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[15]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[14]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[13]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[12]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[11]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[10]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[9]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[8]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[7]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[6]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[5]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[4]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[3]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[2]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[1]}]
set_input_delay -clock clk  0.06  [get_ports {i_cmd[0]}]
set_output_delay -clock clk  0.06  [get_ports {o_valid[7]}]
set_output_delay -clock clk  0.06  [get_ports {o_valid[6]}]
set_output_delay -clock clk  0.06  [get_ports {o_valid[5]}]
set_output_delay -clock clk  0.06  [get_ports {o_valid[4]}]
set_output_delay -clock clk  0.06  [get_ports {o_valid[3]}]
set_output_delay -clock clk  0.06  [get_ports {o_valid[2]}]
set_output_delay -clock clk  0.06  [get_ports {o_valid[1]}]
set_output_delay -clock clk  0.06  [get_ports {o_valid[0]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[255]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[254]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[253]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[252]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[251]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[250]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[249]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[248]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[247]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[246]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[245]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[244]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[243]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[242]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[241]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[240]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[239]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[238]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[237]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[236]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[235]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[234]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[233]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[232]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[231]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[230]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[229]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[228]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[227]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[226]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[225]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[224]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[223]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[222]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[221]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[220]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[219]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[218]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[217]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[216]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[215]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[214]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[213]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[212]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[211]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[210]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[209]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[208]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[207]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[206]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[205]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[204]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[203]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[202]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[201]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[200]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[199]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[198]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[197]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[196]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[195]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[194]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[193]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[192]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[191]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[190]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[189]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[188]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[187]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[186]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[185]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[184]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[183]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[182]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[181]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[180]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[179]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[178]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[177]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[176]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[175]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[174]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[173]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[172]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[171]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[170]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[169]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[168]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[167]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[166]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[165]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[164]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[163]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[162]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[161]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[160]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[159]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[158]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[157]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[156]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[155]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[154]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[153]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[152]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[151]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[150]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[149]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[148]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[147]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[146]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[145]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[144]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[143]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[142]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[141]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[140]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[139]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[138]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[137]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[136]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[135]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[134]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[133]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[132]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[131]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[130]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[129]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[128]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[127]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[126]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[125]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[124]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[123]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[122]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[121]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[120]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[119]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[118]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[117]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[116]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[115]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[114]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[113]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[112]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[111]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[110]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[109]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[108]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[107]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[106]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[105]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[104]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[103]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[102]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[101]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[100]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[99]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[98]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[97]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[96]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[95]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[94]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[93]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[92]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[91]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[90]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[89]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[88]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[87]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[86]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[85]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[84]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[83]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[82]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[81]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[80]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[79]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[78]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[77]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[76]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[75]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[74]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[73]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[72]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[71]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[70]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[69]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[68]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[67]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[66]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[65]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[64]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[63]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[62]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[61]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[60]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[59]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[58]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[57]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[56]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[55]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[54]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[53]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[52]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[51]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[50]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[49]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[48]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[47]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[46]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[45]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[44]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[43]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[42]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[41]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[40]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[39]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[38]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[37]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[36]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[35]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[34]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[33]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[32]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[31]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[30]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[29]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[28]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[27]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[26]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[25]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[24]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[23]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[22]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[21]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[20]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[19]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[18]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[17]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[16]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[15]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[14]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[13]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[12]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[11]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[10]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[9]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[8]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[7]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[6]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[5]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[4]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[3]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[2]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[1]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[0]}]
