/*
###############################################################
#  Generated by:      Cadence Innovus 17.16-s058_1
#  OS:                Linux x86_64(Host ID kl3313-05.ece.gatech.edu)
#  Generated on:      Sun May 23 15:41:53 2021
#  Design:            gen_dft
#  Command:           saveDesign -rc -verilog -def ./data/dbs/postroute/gen_dft -nocompress
###############################################################
*/
module gen_dft_clk (
	CLK, 
	reset, 
	upload, 
	dft_clk_out, 
	ready);
   input CLK;
   input reset;
   input upload;
   output dft_clk_out;
   output ready;

   // Internal wires
   wire N13;
   wire n9;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire [3:0] count;

   DFCNQD1BWP30P140LVT count_reg_0_ (.CDN(n9),
	.CP(CLK),
	.D(n18),
	.Q(count[0]));
   DFCNQD1BWP30P140LVT count_reg_1_ (.CDN(n9),
	.CP(CLK),
	.D(n15),
	.Q(count[1]));
   DFCNQD1BWP30P140LVT count_reg_2_ (.CDN(n9),
	.CP(CLK),
	.D(n16),
	.Q(count[2]));
   DFCNQD1BWP30P140LVT count_reg_3_ (.CDN(n9),
	.CP(CLK),
	.D(n17),
	.Q(count[3]));
   EDFCNQD1BWP30P140LVT run_reg (.CDN(n9),
	.CP(CLK),
	.D(N13),
	.E(upload),
	.Q(dft_clk_out));
   ND2D0BWP30P140LVT U3 (.A1(count[0]),
	.A2(count[1]),
	.ZN(n5));
   INVD0BWP30P140LVT U4 (.I(reset),
	.ZN(n9));
   INR4D0BWP30P140LVT U5 (.A1(count[3]),
	.B1(count[0]),
	.B2(count[1]),
	.B3(count[2]),
	.ZN(n19));
   NR2D0BWP30P140LVT U6 (.A1(n19),
	.A2(dft_clk_out),
	.ZN(N13));
   INVD0BWP30P140LVT U7 (.I(upload),
	.ZN(n2));
   NR3D0BWP30P140LVT U8 (.A1(count[0]),
	.A2(n19),
	.A3(n2),
	.ZN(n18));
   CKND0BWP30P140LVT U9 (.I(count[2]),
	.ZN(n4));
   NR2D0BWP30P140LVT U10 (.A1(n5),
	.A2(n4),
	.ZN(n3));
   OAI21D0BWP30P140LVT U11 (.A1(n3),
	.A2(count[3]),
	.B(upload),
	.ZN(n1));
   AOI21D0BWP30P140LVT U12 (.A1(n3),
	.A2(count[3]),
	.B(n1),
	.ZN(n17));
   AOI211D0BWP30P140LVT U13 (.A1(n5),
	.A2(n4),
	.B(n3),
	.C(n2),
	.ZN(n16));
   OA211D0BWP30P140LVT U14 (.A1(count[0]),
	.A2(count[1]),
	.B(upload),
	.C(n5),
	.Z(n15));
endmodule

module spi_module (
	config_delay_matrix_element0, 
	config_delay_matrix_element1, 
	config_delay_matrix_element2, 
	config_delay_matrix_element3, 
	config_obj_id_element0, 
	config_obj_id_element1, 
	config_obj_id_element2, 
	config_obj_id_element3, 
	CLK, 
	reset, 
	delay_matrix_element, 
	obj_id_element, 
	load);
   input [13:0] config_delay_matrix_element0;
   input [13:0] config_delay_matrix_element1;
   input [13:0] config_delay_matrix_element2;
   input [13:0] config_delay_matrix_element3;
   input [1:0] config_obj_id_element0;
   input [1:0] config_obj_id_element1;
   input [1:0] config_obj_id_element2;
   input [1:0] config_obj_id_element3;
   input CLK;
   input reset;
   output [13:0] delay_matrix_element;
   output [1:0] obj_id_element;
   input load;

   // Internal wires
   wire FE_OFN16_n38;
   wire N23;
   wire N24;
   wire N25;
   wire N26;
   wire N27;
   wire N28;
   wire N29;
   wire N30;
   wire N31;
   wire N32;
   wire N33;
   wire N34;
   wire N35;
   wire N36;
   wire N37;
   wire N38;
   wire N39;
   wire N40;
   wire n120;
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n37;
   wire n38;
   wire [1:0] cnt;
   wire [7:0] din_obj_reg;
   wire [55:0] din_reg;

   BUFFD0P7BWP30P140LVT placeopt_FE_OFC16_n38 (.I(n38),
	.Z(FE_OFN16_n38));
   LHCNDQD1BWP30P140LVT din_obj_reg_reg_3__1_ (.CDN(n38),
	.D(config_obj_id_element3[1]),
	.E(load),
	.Q(din_obj_reg[7]));
   LHCNDQD1BWP30P140LVT din_obj_reg_reg_3__0_ (.CDN(n38),
	.D(config_obj_id_element3[0]),
	.E(load),
	.Q(din_obj_reg[6]));
   LHCNDQD1BWP30P140LVT din_obj_reg_reg_2__1_ (.CDN(n38),
	.D(config_obj_id_element2[1]),
	.E(load),
	.Q(din_obj_reg[5]));
   LHCNDQD1BWP30P140LVT din_obj_reg_reg_2__0_ (.CDN(n38),
	.D(config_obj_id_element2[0]),
	.E(load),
	.Q(din_obj_reg[4]));
   LHCNDQD1BWP30P140LVT din_obj_reg_reg_1__1_ (.CDN(n38),
	.D(config_obj_id_element1[1]),
	.E(load),
	.Q(din_obj_reg[3]));
   LHCNDQD1BWP30P140LVT din_obj_reg_reg_1__0_ (.CDN(n38),
	.D(config_obj_id_element1[0]),
	.E(load),
	.Q(din_obj_reg[2]));
   LHCNDQD1BWP30P140LVT din_obj_reg_reg_0__1_ (.CDN(n38),
	.D(config_obj_id_element0[1]),
	.E(load),
	.Q(din_obj_reg[1]));
   LHCNDQD1BWP30P140LVT din_obj_reg_reg_0__0_ (.CDN(n38),
	.D(config_obj_id_element0[0]),
	.E(load),
	.Q(din_obj_reg[0]));
   LHCNDQD1BWP30P140LVT din_reg_reg_3__13_ (.CDN(n38),
	.D(config_delay_matrix_element3[13]),
	.E(load),
	.Q(din_reg[55]));
   LHCNDQD1BWP30P140LVT din_reg_reg_3__12_ (.CDN(n38),
	.D(config_delay_matrix_element3[12]),
	.E(load),
	.Q(din_reg[54]));
   LHCNDQD1BWP30P140LVT din_reg_reg_3__11_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element3[11]),
	.E(load),
	.Q(din_reg[53]));
   LHCNDQD1BWP30P140LVT din_reg_reg_3__10_ (.CDN(n38),
	.D(config_delay_matrix_element3[10]),
	.E(load),
	.Q(din_reg[52]));
   LHCNDQD1BWP30P140LVT din_reg_reg_3__9_ (.CDN(n38),
	.D(config_delay_matrix_element3[9]),
	.E(load),
	.Q(din_reg[51]));
   LHCNDQD1BWP30P140LVT din_reg_reg_3__8_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element3[8]),
	.E(load),
	.Q(din_reg[50]));
   LHCNDQD1BWP30P140LVT din_reg_reg_3__7_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element3[7]),
	.E(load),
	.Q(din_reg[49]));
   LHCNDQD1BWP30P140LVT din_reg_reg_3__6_ (.CDN(n38),
	.D(config_delay_matrix_element3[6]),
	.E(load),
	.Q(din_reg[48]));
   LHCNDQD1BWP30P140LVT din_reg_reg_3__5_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element3[5]),
	.E(load),
	.Q(din_reg[47]));
   LHCNDQD1BWP30P140LVT din_reg_reg_3__4_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element3[4]),
	.E(load),
	.Q(din_reg[46]));
   LHCNDQD1BWP30P140LVT din_reg_reg_3__3_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element3[3]),
	.E(load),
	.Q(din_reg[45]));
   LHCNDQD1BWP30P140LVT din_reg_reg_3__2_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element3[2]),
	.E(load),
	.Q(din_reg[44]));
   LHCNDQD1BWP30P140LVT din_reg_reg_3__1_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element3[1]),
	.E(load),
	.Q(din_reg[43]));
   LHCNDQD1BWP30P140LVT din_reg_reg_3__0_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element3[0]),
	.E(load),
	.Q(din_reg[42]));
   LHCNDQD1BWP30P140LVT din_reg_reg_2__13_ (.CDN(n38),
	.D(config_delay_matrix_element2[13]),
	.E(load),
	.Q(din_reg[41]));
   LHCNDQD1BWP30P140LVT din_reg_reg_2__12_ (.CDN(n38),
	.D(config_delay_matrix_element2[12]),
	.E(load),
	.Q(din_reg[40]));
   LHCNDQD1BWP30P140LVT din_reg_reg_2__11_ (.CDN(n38),
	.D(config_delay_matrix_element2[11]),
	.E(load),
	.Q(din_reg[39]));
   LHCNDQD1BWP30P140LVT din_reg_reg_2__10_ (.CDN(n38),
	.D(config_delay_matrix_element2[10]),
	.E(load),
	.Q(din_reg[38]));
   LHCNDQD1BWP30P140LVT din_reg_reg_2__9_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element2[9]),
	.E(load),
	.Q(din_reg[37]));
   LHCNDQD1BWP30P140LVT din_reg_reg_2__8_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element2[8]),
	.E(load),
	.Q(din_reg[36]));
   LHCNDQD1BWP30P140LVT din_reg_reg_2__7_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element2[7]),
	.E(load),
	.Q(din_reg[35]));
   LHCNDQD1BWP30P140LVT din_reg_reg_2__6_ (.CDN(n38),
	.D(config_delay_matrix_element2[6]),
	.E(load),
	.Q(din_reg[34]));
   LHCNDQD1BWP30P140LVT din_reg_reg_2__5_ (.CDN(n38),
	.D(config_delay_matrix_element2[5]),
	.E(load),
	.Q(din_reg[33]));
   LHCNDQD1BWP30P140LVT din_reg_reg_2__4_ (.CDN(n38),
	.D(config_delay_matrix_element2[4]),
	.E(load),
	.Q(din_reg[32]));
   LHCNDQD1BWP30P140LVT din_reg_reg_2__3_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element2[3]),
	.E(load),
	.Q(din_reg[31]));
   LHCNDQD1BWP30P140LVT din_reg_reg_2__2_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element2[2]),
	.E(load),
	.Q(din_reg[30]));
   LHCNDQD1BWP30P140LVT din_reg_reg_2__1_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element2[1]),
	.E(load),
	.Q(din_reg[29]));
   LHCNDQD1BWP30P140LVT din_reg_reg_2__0_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element2[0]),
	.E(load),
	.Q(din_reg[28]));
   LHCNDQD1BWP30P140LVT din_reg_reg_1__13_ (.CDN(n38),
	.D(config_delay_matrix_element1[13]),
	.E(load),
	.Q(din_reg[27]));
   LHCNDQD1BWP30P140LVT din_reg_reg_1__12_ (.CDN(n38),
	.D(config_delay_matrix_element1[12]),
	.E(load),
	.Q(din_reg[26]));
   LHCNDQD1BWP30P140LVT din_reg_reg_1__11_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element1[11]),
	.E(load),
	.Q(din_reg[25]));
   LHCNDQD1BWP30P140LVT din_reg_reg_1__10_ (.CDN(n38),
	.D(config_delay_matrix_element1[10]),
	.E(load),
	.Q(din_reg[24]));
   LHCNDQD1BWP30P140LVT din_reg_reg_1__9_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element1[9]),
	.E(load),
	.Q(din_reg[23]));
   LHCNDQD1BWP30P140LVT din_reg_reg_1__8_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element1[8]),
	.E(load),
	.Q(din_reg[22]));
   LHCNDQD1BWP30P140LVT din_reg_reg_1__7_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element1[7]),
	.E(load),
	.Q(din_reg[21]));
   LHCNDQD1BWP30P140LVT din_reg_reg_1__6_ (.CDN(n38),
	.D(config_delay_matrix_element1[6]),
	.E(load),
	.Q(din_reg[20]));
   LHCNDQD1BWP30P140LVT din_reg_reg_1__5_ (.CDN(n38),
	.D(config_delay_matrix_element1[5]),
	.E(load),
	.Q(din_reg[19]));
   LHCNDQD1BWP30P140LVT din_reg_reg_1__4_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element1[4]),
	.E(load),
	.Q(din_reg[18]));
   LHCNDQD1BWP30P140LVT din_reg_reg_1__3_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element1[3]),
	.E(load),
	.Q(din_reg[17]));
   LHCNDQD1BWP30P140LVT din_reg_reg_1__2_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element1[2]),
	.E(load),
	.Q(din_reg[16]));
   LHCNDQD1BWP30P140LVT din_reg_reg_1__1_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element1[1]),
	.E(load),
	.Q(din_reg[15]));
   LHCNDQD1BWP30P140LVT din_reg_reg_1__0_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element1[0]),
	.E(load),
	.Q(din_reg[14]));
   LHCNDQD1BWP30P140LVT din_reg_reg_0__13_ (.CDN(n38),
	.D(config_delay_matrix_element0[13]),
	.E(load),
	.Q(din_reg[13]));
   LHCNDQD1BWP30P140LVT din_reg_reg_0__12_ (.CDN(n38),
	.D(config_delay_matrix_element0[12]),
	.E(load),
	.Q(din_reg[12]));
   LHCNDQD1BWP30P140LVT din_reg_reg_0__11_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element0[11]),
	.E(load),
	.Q(din_reg[11]));
   LHCNDQD1BWP30P140LVT din_reg_reg_0__10_ (.CDN(n38),
	.D(config_delay_matrix_element0[10]),
	.E(load),
	.Q(din_reg[10]));
   LHCNDQD1BWP30P140LVT din_reg_reg_0__9_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element0[9]),
	.E(load),
	.Q(din_reg[9]));
   LHCNDQD1BWP30P140LVT din_reg_reg_0__8_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element0[8]),
	.E(load),
	.Q(din_reg[8]));
   LHCNDQD1BWP30P140LVT din_reg_reg_0__7_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element0[7]),
	.E(load),
	.Q(din_reg[7]));
   LHCNDQD1BWP30P140LVT din_reg_reg_0__6_ (.CDN(n38),
	.D(config_delay_matrix_element0[6]),
	.E(load),
	.Q(din_reg[6]));
   LHCNDQD1BWP30P140LVT din_reg_reg_0__5_ (.CDN(n38),
	.D(config_delay_matrix_element0[5]),
	.E(load),
	.Q(din_reg[5]));
   LHCNDQD1BWP30P140LVT din_reg_reg_0__4_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element0[4]),
	.E(load),
	.Q(din_reg[4]));
   LHCNDQD1BWP30P140LVT din_reg_reg_0__3_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element0[3]),
	.E(load),
	.Q(din_reg[3]));
   LHCNDQD1BWP30P140LVT din_reg_reg_0__2_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element0[2]),
	.E(load),
	.Q(din_reg[2]));
   LHCNDQD1BWP30P140LVT din_reg_reg_0__1_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element0[1]),
	.E(load),
	.Q(din_reg[1]));
   LHCNDQD1BWP30P140LVT din_reg_reg_0__0_ (.CDN(FE_OFN16_n38),
	.D(config_delay_matrix_element0[0]),
	.E(load),
	.Q(din_reg[0]));
   EDFCNQD1BWP30P140LVT delay_matrix_element_reg_0_ (.CDN(FE_OFN16_n38),
	.CP(CLK),
	.D(N23),
	.E(n120),
	.Q(delay_matrix_element[0]));
   EDFCNQD1BWP30P140LVT cnt_reg_1_ (.CDN(FE_OFN16_n38),
	.CP(CLK),
	.D(N40),
	.E(n120),
	.Q(cnt[1]));
   EDFCNQD1BWP30P140LVT cnt_reg_0_ (.CDN(FE_OFN16_n38),
	.CP(CLK),
	.D(N39),
	.E(n120),
	.Q(cnt[0]));
   EDFCNQD1BWP30P140LVT obj_id_element_reg_1_ (.CDN(FE_OFN16_n38),
	.CP(CLK),
	.D(N38),
	.E(n120),
	.Q(obj_id_element[1]));
   EDFCNQD1BWP30P140LVT obj_id_element_reg_0_ (.CDN(FE_OFN16_n38),
	.CP(CLK),
	.D(N37),
	.E(n120),
	.Q(obj_id_element[0]));
   EDFCNQD1BWP30P140LVT delay_matrix_element_reg_13_ (.CDN(FE_OFN16_n38),
	.CP(CLK),
	.D(N36),
	.E(n120),
	.Q(delay_matrix_element[13]));
   EDFCNQD1BWP30P140LVT delay_matrix_element_reg_12_ (.CDN(FE_OFN16_n38),
	.CP(CLK),
	.D(N35),
	.E(n120),
	.Q(delay_matrix_element[12]));
   EDFCNQD1BWP30P140LVT delay_matrix_element_reg_11_ (.CDN(FE_OFN16_n38),
	.CP(CLK),
	.D(N34),
	.E(n120),
	.Q(delay_matrix_element[11]));
   EDFCNQD1BWP30P140LVT delay_matrix_element_reg_10_ (.CDN(FE_OFN16_n38),
	.CP(CLK),
	.D(N33),
	.E(n120),
	.Q(delay_matrix_element[10]));
   EDFCNQD1BWP30P140LVT delay_matrix_element_reg_9_ (.CDN(FE_OFN16_n38),
	.CP(CLK),
	.D(N32),
	.E(n120),
	.Q(delay_matrix_element[9]));
   EDFCNQD1BWP30P140LVT delay_matrix_element_reg_8_ (.CDN(FE_OFN16_n38),
	.CP(CLK),
	.D(N31),
	.E(n120),
	.Q(delay_matrix_element[8]));
   EDFCNQD1BWP30P140LVT delay_matrix_element_reg_7_ (.CDN(FE_OFN16_n38),
	.CP(CLK),
	.D(N30),
	.E(n120),
	.Q(delay_matrix_element[7]));
   EDFCNQD1BWP30P140LVT delay_matrix_element_reg_6_ (.CDN(FE_OFN16_n38),
	.CP(CLK),
	.D(N29),
	.E(n120),
	.Q(delay_matrix_element[6]));
   EDFCNQD1BWP30P140LVT delay_matrix_element_reg_5_ (.CDN(FE_OFN16_n38),
	.CP(CLK),
	.D(N28),
	.E(n120),
	.Q(delay_matrix_element[5]));
   EDFCNQD1BWP30P140LVT delay_matrix_element_reg_4_ (.CDN(FE_OFN16_n38),
	.CP(CLK),
	.D(N27),
	.E(n120),
	.Q(delay_matrix_element[4]));
   EDFCNQD1BWP30P140LVT delay_matrix_element_reg_3_ (.CDN(FE_OFN16_n38),
	.CP(CLK),
	.D(N26),
	.E(n120),
	.Q(delay_matrix_element[3]));
   EDFCNQD1BWP30P140LVT delay_matrix_element_reg_2_ (.CDN(FE_OFN16_n38),
	.CP(CLK),
	.D(N25),
	.E(n120),
	.Q(delay_matrix_element[2]));
   EDFCNQD1BWP30P140LVT delay_matrix_element_reg_1_ (.CDN(FE_OFN16_n38),
	.CP(CLK),
	.D(N24),
	.E(n120),
	.Q(delay_matrix_element[1]));
   INVD0BWP30P140LVT U3 (.I(cnt[0]),
	.ZN(N39));
   INVD0BWP30P140LVT U4 (.I(reset),
	.ZN(n38));
   ND2D0BWP30P140LVT U5 (.A1(load),
	.A2(FE_OFN16_n38),
	.ZN(n120));
   NR2D0BWP30P140LVT U6 (.A1(cnt[1]),
	.A2(N39),
	.ZN(n37));
   CKND0BWP30P140LVT U7 (.I(cnt[1]),
	.ZN(n1));
   NR2D0BWP30P140LVT U8 (.A1(cnt[0]),
	.A2(n1),
	.ZN(n36));
   AOI22D0BWP30P140LVT U9 (.A1(n37),
	.A2(din_reg[26]),
	.B1(n36),
	.B2(din_reg[40]),
	.ZN(n3));
   NR2D0BWP30P140LVT U10 (.A1(N39),
	.A2(n1),
	.ZN(n33));
   NR2D0BWP30P140LVT U11 (.A1(cnt[0]),
	.A2(cnt[1]),
	.ZN(n32));
   AOI22D0BWP30P140LVT U12 (.A1(n33),
	.A2(din_reg[54]),
	.B1(n32),
	.B2(din_reg[12]),
	.ZN(n2));
   ND2D0BWP30P140LVT U13 (.A1(n3),
	.A2(n2),
	.ZN(N35));
   AOI22D0BWP30P140LVT U14 (.A1(n37),
	.A2(din_reg[27]),
	.B1(n36),
	.B2(din_reg[41]),
	.ZN(n5));
   AOI22D0BWP30P140LVT U15 (.A1(n33),
	.A2(din_reg[55]),
	.B1(n32),
	.B2(din_reg[13]),
	.ZN(n4));
   ND2D0BWP30P140LVT U16 (.A1(n5),
	.A2(n4),
	.ZN(N36));
   AOI22D0BWP30P140LVT U17 (.A1(n37),
	.A2(din_obj_reg[2]),
	.B1(n36),
	.B2(din_obj_reg[4]),
	.ZN(n7));
   AOI22D0BWP30P140LVT U18 (.A1(n33),
	.A2(din_obj_reg[6]),
	.B1(n32),
	.B2(din_obj_reg[0]),
	.ZN(n6));
   ND2D0BWP30P140LVT U19 (.A1(n7),
	.A2(n6),
	.ZN(N37));
   AOI22D0BWP30P140LVT U20 (.A1(n37),
	.A2(din_obj_reg[3]),
	.B1(n36),
	.B2(din_obj_reg[5]),
	.ZN(n9));
   AOI22D0BWP30P140LVT U21 (.A1(n33),
	.A2(din_obj_reg[7]),
	.B1(n32),
	.B2(din_obj_reg[1]),
	.ZN(n8));
   ND2D0BWP30P140LVT U22 (.A1(n9),
	.A2(n8),
	.ZN(N38));
   AOI22D0BWP30P140LVT U23 (.A1(n37),
	.A2(din_reg[14]),
	.B1(n36),
	.B2(din_reg[28]),
	.ZN(n11));
   AOI22D0BWP30P140LVT U24 (.A1(n33),
	.A2(din_reg[42]),
	.B1(n32),
	.B2(din_reg[0]),
	.ZN(n10));
   ND2D0BWP30P140LVT U25 (.A1(n11),
	.A2(n10),
	.ZN(N23));
   AOI22D0BWP30P140LVT U26 (.A1(n37),
	.A2(din_reg[22]),
	.B1(n36),
	.B2(din_reg[36]),
	.ZN(n13));
   AOI22D0BWP30P140LVT U27 (.A1(n33),
	.A2(din_reg[50]),
	.B1(n32),
	.B2(din_reg[8]),
	.ZN(n12));
   ND2D0BWP30P140LVT U28 (.A1(n13),
	.A2(n12),
	.ZN(N31));
   AOI22D0BWP30P140LVT U29 (.A1(n37),
	.A2(din_reg[21]),
	.B1(n36),
	.B2(din_reg[35]),
	.ZN(n15));
   AOI22D0BWP30P140LVT U30 (.A1(n33),
	.A2(din_reg[49]),
	.B1(n32),
	.B2(din_reg[7]),
	.ZN(n14));
   ND2D0BWP30P140LVT U31 (.A1(n15),
	.A2(n14),
	.ZN(N30));
   AOI22D0BWP30P140LVT U32 (.A1(n37),
	.A2(din_reg[24]),
	.B1(n36),
	.B2(din_reg[38]),
	.ZN(n17));
   AOI22D0BWP30P140LVT U33 (.A1(n33),
	.A2(din_reg[52]),
	.B1(n32),
	.B2(din_reg[10]),
	.ZN(n16));
   ND2D0BWP30P140LVT U34 (.A1(n17),
	.A2(n16),
	.ZN(N33));
   AOI22D0BWP30P140LVT U35 (.A1(n37),
	.A2(din_reg[23]),
	.B1(n36),
	.B2(din_reg[37]),
	.ZN(n19));
   AOI22D0BWP30P140LVT U36 (.A1(n33),
	.A2(din_reg[51]),
	.B1(n32),
	.B2(din_reg[9]),
	.ZN(n18));
   ND2D0BWP30P140LVT U37 (.A1(n19),
	.A2(n18),
	.ZN(N32));
   AOI22D0BWP30P140LVT U38 (.A1(n37),
	.A2(din_reg[15]),
	.B1(n36),
	.B2(din_reg[29]),
	.ZN(n21));
   AOI22D0BWP30P140LVT U39 (.A1(n33),
	.A2(din_reg[43]),
	.B1(n32),
	.B2(din_reg[1]),
	.ZN(n20));
   ND2D0BWP30P140LVT U40 (.A1(n21),
	.A2(n20),
	.ZN(N24));
   AOI22D0BWP30P140LVT U41 (.A1(n37),
	.A2(din_reg[25]),
	.B1(n36),
	.B2(din_reg[39]),
	.ZN(n23));
   AOI22D0BWP30P140LVT U42 (.A1(n33),
	.A2(din_reg[53]),
	.B1(n32),
	.B2(din_reg[11]),
	.ZN(n22));
   ND2D0BWP30P140LVT U43 (.A1(n23),
	.A2(n22),
	.ZN(N34));
   AOI22D0BWP30P140LVT U44 (.A1(n37),
	.A2(din_reg[17]),
	.B1(n36),
	.B2(din_reg[31]),
	.ZN(n25));
   AOI22D0BWP30P140LVT U45 (.A1(n33),
	.A2(din_reg[45]),
	.B1(n32),
	.B2(din_reg[3]),
	.ZN(n24));
   ND2D0BWP30P140LVT U46 (.A1(n25),
	.A2(n24),
	.ZN(N26));
   AOI22D0BWP30P140LVT U47 (.A1(n37),
	.A2(din_reg[16]),
	.B1(n36),
	.B2(din_reg[30]),
	.ZN(n27));
   AOI22D0BWP30P140LVT U48 (.A1(n33),
	.A2(din_reg[44]),
	.B1(n32),
	.B2(din_reg[2]),
	.ZN(n26));
   ND2D0BWP30P140LVT U49 (.A1(n27),
	.A2(n26),
	.ZN(N25));
   AOI22D0BWP30P140LVT U50 (.A1(n37),
	.A2(din_reg[19]),
	.B1(n36),
	.B2(din_reg[33]),
	.ZN(n29));
   AOI22D0BWP30P140LVT U51 (.A1(n33),
	.A2(din_reg[47]),
	.B1(n32),
	.B2(din_reg[5]),
	.ZN(n28));
   ND2D0BWP30P140LVT U52 (.A1(n29),
	.A2(n28),
	.ZN(N28));
   AOI22D0BWP30P140LVT U53 (.A1(n37),
	.A2(din_reg[18]),
	.B1(n36),
	.B2(din_reg[32]),
	.ZN(n31));
   AOI22D0BWP30P140LVT U54 (.A1(n33),
	.A2(din_reg[46]),
	.B1(n32),
	.B2(din_reg[4]),
	.ZN(n30));
   ND2D0BWP30P140LVT U55 (.A1(n31),
	.A2(n30),
	.ZN(N27));
   AOI22D0BWP30P140LVT U56 (.A1(n37),
	.A2(din_reg[20]),
	.B1(n36),
	.B2(din_reg[34]),
	.ZN(n35));
   AOI22D0BWP30P140LVT U57 (.A1(n33),
	.A2(din_reg[48]),
	.B1(n32),
	.B2(din_reg[6]),
	.ZN(n34));
   ND2D0BWP30P140LVT U58 (.A1(n35),
	.A2(n34),
	.ZN(N29));
   OR2D0BWP30P140LVT U59 (.A1(n37),
	.A2(n36),
	.Z(N40));
endmodule

module gen_dft (
	CLK, 
	reset, 
	upload, 
	config_delay_matrix_element0, 
	config_delay_matrix_element1, 
	config_delay_matrix_element2, 
	config_delay_matrix_element3, 
	config_obj_id_element0, 
	config_obj_id_element1, 
	config_obj_id_element2, 
	config_obj_id_element3, 
	delay_matrix_element, 
	obj_id_element, 
	load, 
	dft_clk_out);
   input CLK;
   input reset;
   input upload;
   input [13:0] config_delay_matrix_element0;
   input [13:0] config_delay_matrix_element1;
   input [13:0] config_delay_matrix_element2;
   input [13:0] config_delay_matrix_element3;
   input [1:0] config_obj_id_element0;
   input [1:0] config_obj_id_element1;
   input [1:0] config_obj_id_element2;
   input [1:0] config_obj_id_element3;
   output [13:0] delay_matrix_element;
   output [1:0] obj_id_element;
   input load;
   output dft_clk_out;

   // Internal wires
   wire FE_OFN17_delay_matrix_element_7;
   wire FE_OFN15_delay_matrix_element_0;
   wire FE_OFN14_delay_matrix_element_3;
   wire FE_OFN13_delay_matrix_element_1;
   wire FE_OFN12_delay_matrix_element_4;
   wire FE_OFN11_delay_matrix_element_6;
   wire FE_OFN10_delay_matrix_element_2;
   wire FE_OFN9_obj_id_element_0;
   wire FE_OFN8_delay_matrix_element_10;
   wire FE_OFN7_delay_matrix_element_8;
   wire FE_OFN6_delay_matrix_element_9;
   wire FE_OFN5_delay_matrix_element_11;
   wire FE_OFN4_delay_matrix_element_12;
   wire FE_OFN3_delay_matrix_element_5;
   wire FE_OFN2_delay_matrix_element_13;
   wire FE_OFN1_obj_id_element_1;
   wire FE_OFN0_dft_clk_out;

   CKBD2BWP30P140LVT placeopt_FE_OFC17_delay_matrix_element_7 (.I(FE_OFN17_delay_matrix_element_7),
	.Z(delay_matrix_element[7]));
   CKBD2BWP30P140LVT placeopt_FE_OFC15_delay_matrix_element_0 (.I(FE_OFN15_delay_matrix_element_0),
	.Z(delay_matrix_element[0]));
   CKBD2BWP30P140LVT placeopt_FE_OFC14_delay_matrix_element_3 (.I(FE_OFN14_delay_matrix_element_3),
	.Z(delay_matrix_element[3]));
   CKBD2BWP30P140LVT placeopt_FE_OFC13_delay_matrix_element_1 (.I(FE_OFN13_delay_matrix_element_1),
	.Z(delay_matrix_element[1]));
   CKBD2BWP30P140LVT placeopt_FE_OFC12_delay_matrix_element_4 (.I(FE_OFN12_delay_matrix_element_4),
	.Z(delay_matrix_element[4]));
   CKBD2BWP30P140LVT placeopt_FE_OFC11_delay_matrix_element_6 (.I(FE_OFN11_delay_matrix_element_6),
	.Z(delay_matrix_element[6]));
   CKBD2BWP30P140LVT placeopt_FE_OFC10_delay_matrix_element_2 (.I(FE_OFN10_delay_matrix_element_2),
	.Z(delay_matrix_element[2]));
   CKBD2BWP30P140LVT placeopt_FE_OFC9_obj_id_element_0 (.I(FE_OFN9_obj_id_element_0),
	.Z(obj_id_element[0]));
   CKBD2BWP30P140LVT placeopt_FE_OFC8_delay_matrix_element_10 (.I(FE_OFN8_delay_matrix_element_10),
	.Z(delay_matrix_element[10]));
   CKBD2BWP30P140LVT placeopt_FE_OFC7_delay_matrix_element_8 (.I(FE_OFN7_delay_matrix_element_8),
	.Z(delay_matrix_element[8]));
   CKBD2BWP30P140LVT placeopt_FE_OFC6_delay_matrix_element_9 (.I(FE_OFN6_delay_matrix_element_9),
	.Z(delay_matrix_element[9]));
   CKBD2BWP30P140LVT placeopt_FE_OFC5_delay_matrix_element_11 (.I(FE_OFN5_delay_matrix_element_11),
	.Z(delay_matrix_element[11]));
   CKBD2BWP30P140LVT placeopt_FE_OFC4_delay_matrix_element_12 (.I(FE_OFN4_delay_matrix_element_12),
	.Z(delay_matrix_element[12]));
   CKBD2BWP30P140LVT placeopt_FE_OFC3_delay_matrix_element_5 (.I(FE_OFN3_delay_matrix_element_5),
	.Z(delay_matrix_element[5]));
   CKBD2BWP30P140LVT placeopt_FE_OFC2_delay_matrix_element_13 (.I(FE_OFN2_delay_matrix_element_13),
	.Z(delay_matrix_element[13]));
   CKBD2BWP30P140LVT placeopt_FE_OFC1_obj_id_element_1 (.I(FE_OFN1_obj_id_element_1),
	.Z(obj_id_element[1]));
   CKBD3BWP30P140LVT placeopt_FE_OFC0_dft_clk_out (.I(FE_OFN0_dft_clk_out),
	.Z(dft_clk_out));
   gen_dft_clk UUT1 (.CLK(CLK),
	.reset(reset),
	.upload(upload),
	.dft_clk_out(FE_OFN0_dft_clk_out));
   spi_module UUT2 (.config_delay_matrix_element0(config_delay_matrix_element0),
	.config_delay_matrix_element1(config_delay_matrix_element1),
	.config_delay_matrix_element2(config_delay_matrix_element2),
	.config_delay_matrix_element3(config_delay_matrix_element3),
	.config_obj_id_element0(config_obj_id_element0),
	.config_obj_id_element1(config_obj_id_element1),
	.config_obj_id_element2(config_obj_id_element2),
	.config_obj_id_element3(config_obj_id_element3),
	.CLK(FE_OFN0_dft_clk_out),
	.reset(reset),
	.delay_matrix_element({ FE_OFN2_delay_matrix_element_13,
		FE_OFN4_delay_matrix_element_12,
		FE_OFN5_delay_matrix_element_11,
		FE_OFN8_delay_matrix_element_10,
		FE_OFN6_delay_matrix_element_9,
		FE_OFN7_delay_matrix_element_8,
		FE_OFN17_delay_matrix_element_7,
		FE_OFN11_delay_matrix_element_6,
		FE_OFN3_delay_matrix_element_5,
		FE_OFN12_delay_matrix_element_4,
		FE_OFN14_delay_matrix_element_3,
		FE_OFN10_delay_matrix_element_2,
		FE_OFN13_delay_matrix_element_1,
		FE_OFN15_delay_matrix_element_0 }),
	.obj_id_element({ FE_OFN1_obj_id_element_1,
		FE_OFN9_obj_id_element_0 }),
	.load(load));
endmodule

