###################################################################

# Created by write_sdc on Sat May 22 22:59:41 2021

###################################################################
set sdc_version 2.0

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_driving_cell -min -lib_cell BUFFD2BWP30P140LVT [get_ports clk]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports rst]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_valid[1]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_valid[0]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[63]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[62]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[61]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[60]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[59]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[58]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[57]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[56]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[55]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[54]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[53]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[52]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[51]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[50]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[49]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[48]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[47]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[46]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[45]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[44]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[43]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[42]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[41]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[40]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[39]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[38]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[37]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[36]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[35]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[34]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[33]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[32]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[31]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[30]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[29]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[28]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[27]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[26]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[25]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[24]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[23]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[22]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[21]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[20]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[19]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[18]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[17]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[16]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[15]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[14]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[13]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[12]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[11]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[10]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[9]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[8]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[7]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[6]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[5]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[4]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[3]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[2]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[1]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports {i_data_bus[0]}]
set_driving_cell -lib_cell BUFFD2BWP30P140LVT [get_ports i_en]
set_load -pin_load 0.1 [get_ports o_valid]
set_load -pin_load 0.1 [get_ports {o_data_bus[31]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[30]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[29]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[28]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[27]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[26]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[25]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[24]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[23]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[22]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[21]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[20]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[19]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[18]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[17]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[16]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[15]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[14]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[13]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[12]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[11]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[10]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[9]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[8]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[7]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[6]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[5]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[4]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[3]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[2]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[1]}]
set_load -pin_load 0.1 [get_ports {o_data_bus[0]}]
create_clock [get_ports clk]  -name clk  -period 0.3  -waveform {0 0.15}  -add
set_clock_uncertainty -setup 0.15  [get_clocks clk]
set_false_path   -from [list [get_ports rst] [get_ports i_en]]
set_input_delay -clock clk  0.06  [get_ports rst]
set_input_delay -clock clk  0.06  [get_ports i_en]
set_input_delay -clock clk  0.06  [get_ports {i_valid[1]}]
set_input_delay -clock clk  0.06  [get_ports {i_valid[0]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[63]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[62]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[61]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[60]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[59]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[58]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[57]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[56]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[55]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[54]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[53]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[52]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[51]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[50]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[49]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[48]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[47]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[46]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[45]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[44]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[43]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[42]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[41]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[40]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[39]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[38]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[37]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[36]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[35]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[34]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[33]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[32]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[31]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[30]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[29]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[28]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[27]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[26]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[25]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[24]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[23]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[22]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[21]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[20]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[19]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[18]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[17]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[16]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[15]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[14]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[13]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[12]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[11]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[10]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[9]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[8]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[7]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[6]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[5]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[4]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[3]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[2]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[1]}]
set_input_delay -clock clk  0.06  [get_ports {i_data_bus[0]}]
set_output_delay -clock clk  0.06  [get_ports o_valid]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[31]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[30]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[29]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[28]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[27]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[26]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[25]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[24]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[23]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[22]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[21]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[20]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[19]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[18]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[17]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[16]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[15]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[14]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[13]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[12]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[11]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[10]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[9]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[8]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[7]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[6]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[5]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[4]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[3]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[2]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[1]}]
set_output_delay -clock clk  0.06  [get_ports {o_data_bus[0]}]
