env = Environment()

includes = '''
              include
			  src
'''

env.Append(LINKFLAGS=['-lboost_program_options'])
env.Append(CXXFLAGS=['-std=c++17', '-lboost_program_options' ])
env.Append(LIBS=['-lboost_program_options'])
env.Append(CPPPATH = Split(includes))

env.Program('template_c_model', ['./src/template_c_model.cpp'])
