/*
###############################################################
#  Generated by:      Cadence Innovus 17.16-s058_1
#  OS:                Linux x86_64(Host ID kl3313-05.ece.gatech.edu)
#  Generated on:      Mon May 17 12:10:58 2021
#  Design:            gen_dft_clk
#  Command:           saveDesign -rc -verilog -def ./data/dbs/postroute/gen_dft_clk -nocompress
###############################################################
*/
module gen_dft_clk (
	CLK, 
	reset, 
	upload, 
	dft_clk_out, 
	ready);
   input CLK;
   input reset;
   input upload;
   output dft_clk_out;
   output ready;

   // Internal wires
   wire N13;
   wire n9;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire [3:0] count;

   DFCNQD1BWP30P140LVT count_reg_0_ (.CDN(n9),
	.CP(CLK),
	.D(n18),
	.Q(count[0]));
   DFCNQD1BWP30P140LVT count_reg_1_ (.CDN(n9),
	.CP(CLK),
	.D(n15),
	.Q(count[1]));
   DFCNQD1BWP30P140LVT count_reg_2_ (.CDN(n9),
	.CP(CLK),
	.D(n16),
	.Q(count[2]));
   DFCNQD1BWP30P140LVT count_reg_3_ (.CDN(n9),
	.CP(CLK),
	.D(n17),
	.Q(count[3]));
   EDFCNQD2BWP30P140LVT ready_reg (.CDN(n9),
	.CP(CLK),
	.D(n19),
	.E(upload),
	.Q(ready));
   EDFCNQD2BWP30P140LVT run_reg (.CDN(n9),
	.CP(CLK),
	.D(N13),
	.E(upload),
	.Q(dft_clk_out));
   ND2D0BWP30P140LVT U18 (.A1(count[0]),
	.A2(count[1]),
	.ZN(n24));
   INVD0BWP30P140LVT U19 (.I(reset),
	.ZN(n9));
   INR4D0BWP30P140LVT U20 (.A1(count[3]),
	.B1(count[0]),
	.B2(count[1]),
	.B3(count[2]),
	.ZN(n19));
   NR2OPTPAD2BWP30P140LVT U21 (.A1(dft_clk_out),
	.A2(n19),
	.ZN(N13));
   INVD0BWP30P140LVT U22 (.I(upload),
	.ZN(n21));
   NR3D0BWP30P140LVT U23 (.A1(count[0]),
	.A2(n19),
	.A3(n21),
	.ZN(n18));
   INVD0BWP30P140LVT U24 (.I(count[2]),
	.ZN(n23));
   NR2D0BWP30P140LVT U25 (.A1(n24),
	.A2(n23),
	.ZN(n22));
   OAI21D0BWP30P140LVT U26 (.A1(n22),
	.A2(count[3]),
	.B(upload),
	.ZN(n20));
   AOI21D0BWP30P140LVT U27 (.A1(n22),
	.A2(count[3]),
	.B(n20),
	.ZN(n17));
   AOI211D0BWP30P140LVT U28 (.A1(n24),
	.A2(n23),
	.B(n22),
	.C(n21),
	.ZN(n16));
   OA211D0BWP30P140LVT U29 (.A1(count[0]),
	.A2(count[1]),
	.B(upload),
	.C(n24),
	.Z(n15));
endmodule

